[package]
name = "llzk_backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
llzk = { git = "https://github.com/project-llzk/llzk-rs", package = "llzk" }
anyhow = "1"
